// Autogenerated by Thrift Compiler (0.9.2)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package thriftproto

import (
	"bytes"
	"fmt"

	"git.apache.org/thrift.git/lib/go/thrift"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var GoUnusedProtection__ int

type Payload struct {
	Meta      []byte `thrift:"meta,1" json:"meta"`
	XferPipe  []byte `thrift:"xferPipe,2" json:"xferPipe"`
	BodyCodec int32  `thrift:"bodyCodec,3" json:"bodyCodec"`
	Body      []byte `thrift:"body,4" json:"body"`
}

func NewPayload() *Payload {
	return &Payload{}
}

func (p *Payload) GetMeta() []byte {
	return p.Meta
}

func (p *Payload) GetXferPipe() []byte {
	return p.XferPipe
}

func (p *Payload) GetBodyCodec() int32 {
	return p.BodyCodec
}

func (p *Payload) GetBody() []byte {
	return p.Body
}
func (p *Payload) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.ReadField2(iprot); err != nil {
				return err
			}
		case 3:
			if err := p.ReadField3(iprot); err != nil {
				return err
			}
		case 4:
			if err := p.ReadField4(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *Payload) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.Meta = v
	}
	return nil
}

func (p *Payload) ReadField2(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return fmt.Errorf("error reading field 2: %s", err)
	} else {
		p.XferPipe = v
	}
	return nil
}

func (p *Payload) ReadField3(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return fmt.Errorf("error reading field 3: %s", err)
	} else {
		p.BodyCodec = v
	}
	return nil
}

func (p *Payload) ReadField4(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBinary(); err != nil {
		return fmt.Errorf("error reading field 4: %s", err)
	} else {
		p.Body = v
	}
	return nil
}

func (p *Payload) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("payload"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := p.writeField3(oprot); err != nil {
		return err
	}
	if err := p.writeField4(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *Payload) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("meta", thrift.STRING, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:meta: %s", p, err)
	}
	if err := oprot.WriteBinary(p.Meta); err != nil {
		return fmt.Errorf("%T.meta (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:meta: %s", p, err)
	}
	return err
}

func (p *Payload) writeField2(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("xferPipe", thrift.STRING, 2); err != nil {
		return fmt.Errorf("%T write field begin error 2:xferPipe: %s", p, err)
	}
	if err := oprot.WriteBinary(p.XferPipe); err != nil {
		return fmt.Errorf("%T.xferPipe (2) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 2:xferPipe: %s", p, err)
	}
	return err
}

func (p *Payload) writeField3(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("bodyCodec", thrift.I32, 3); err != nil {
		return fmt.Errorf("%T write field begin error 3:bodyCodec: %s", p, err)
	}
	if err := oprot.WriteI32(int32(p.BodyCodec)); err != nil {
		return fmt.Errorf("%T.bodyCodec (3) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 3:bodyCodec: %s", p, err)
	}
	return err
}

func (p *Payload) writeField4(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("body", thrift.STRING, 4); err != nil {
		return fmt.Errorf("%T write field begin error 4:body: %s", p, err)
	}
	if err := oprot.WriteBinary(p.Body); err != nil {
		return fmt.Errorf("%T.body (4) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 4:body: %s", p, err)
	}
	return err
}

func (p *Payload) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Payload(%+v)", *p)
}

type Test struct {
	Author string `thrift:"author,1" json:"author"`
}

func NewTest() *Test {
	return &Test{}
}

func (p *Test) GetAuthor() string {
	return p.Author
}
func (p *Test) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return fmt.Errorf("%T read error: %s", p, err)
	}
	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return fmt.Errorf("%T field %d read error: %s", p, fieldId, err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.ReadField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return fmt.Errorf("%T read struct end error: %s", p, err)
	}
	return nil
}

func (p *Test) ReadField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return fmt.Errorf("error reading field 1: %s", err)
	} else {
		p.Author = v
	}
	return nil
}

func (p *Test) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("test"); err != nil {
		return fmt.Errorf("%T write struct begin error: %s", p, err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return fmt.Errorf("write field stop error: %s", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return fmt.Errorf("write struct stop error: %s", err)
	}
	return nil
}

func (p *Test) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("author", thrift.STRING, 1); err != nil {
		return fmt.Errorf("%T write field begin error 1:author: %s", p, err)
	}
	if err := oprot.WriteString(string(p.Author)); err != nil {
		return fmt.Errorf("%T.author (1) field write error: %s", p, err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return fmt.Errorf("%T write field end error 1:author: %s", p, err)
	}
	return err
}

func (p *Test) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Test(%+v)", *p)
}
